### ISSUE TITLE
Got my IP banned after too many refreshes

### ISSUE THREAD

**Issue by AdityaSinghRathore** [sushrut111/cowin-automation-extn#1]

**Comment by sushrut111** [comment]
Could you please describe the issue? I would love to know more on how this is caused due to extension's functionality.

**Comment by AdityaSinghRathore** [comment]
Well to be honest I did hit refresh a lot. Probably nothing to do with the codebase.

**Comment by sushrut111** [comment]
Okay. I will close the issue then. Please feel free to suggest modifications and improvements through issues or even pull requests. Thanks for using my extension.
