### ISSUE TITLE
Add option to select the preferred vaccine

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/cowin-automation-extn#10]
The extension currently allows selection on filter Age 18 + / Age 45 +.
Add checkboxes to select the different options available
![Screenshot 2021-05-21 at 9 52 13 PM](https://user-images.githubusercontent.com/11269256/119168762-e117a180-ba7e-11eb-9002-1c4941725fa5.png)

**Comment by prayuj** [comment]
I could take this up!

**Comment by sushrut111** [comment]
Sure! Go ahead.

**Comment by kapishmalik** [comment]
@sushrut111 let me know if anything else comes up. I also want to contribute

**Comment by sushrut111** [comment]
Fixed in #13
