### ISSUE TITLE
Confirm booking automatically on captcha page-not working

### ISSUE THREAD

**Issue by Samir027** [sushrut111/cowin-automation-extn#103]
I tried booking the vaccine slot, though the slots are available and I have opted for automated confirmation. The slot is not getting confirmed on cowin

**Comment by Samir027** [comment]
The captcha is removed from the confirmation page. I tried booking the vaccine slot, though the slots are available and I have opted for automated confirmation. The slot is not getting confirmed on cowin

**Comment by AshishNamdev** [comment]
Which version of this extension are you using.?
Pelase use the latest releaed version, it Already have fix for this issue.

**Comment by Samir027** [comment]
I have been using the latest release 4.1.2

**Comment by sushrut111** [comment]
You probably have wrong version installed or you have not uninstalled older version.
If you are sure that you have only one version of extension installed and that is v4.1.2, please record your screen when that happens, preferably with keeping console open (press F12 to open it).

**Comment by DakshK579** [comment]
The guy is not telling more details after all so this issue can be saved as resolved now
