### ISSUE TITLE
Otp not getting generated. Cowin giving error

### ISSUE THREAD

**Issue by cool2srik1** [sushrut111/cowin-automation-extn#108]
It seems cowin has blocked my number and is not allowing me to generate new otp.

Any others facing this issue?
![IMG_20210607_180153](https://user-images.githubusercontent.com/85451523/121017069-7d011700-c7ba-11eb-8aa3-f317e8ffb8fb.jpg)

**Comment by gdosh** [comment]
Yes. Me too.i could log in at 2pm today. But when I tried again at 430 pm... I got error. 
Are they shadow banning phone numbers now ? 
My brother in law can log in from his number, same IP.

**Comment by gdosh** [comment]
The phone number is blocked. 
I've tried 4 diff numbers from same IP. 
All of them recvd OTP. 
But the nunber used with the CoWin extension does not receive OTP. They may have blacklisted these numbers. 
Which would be a very petty move by GOI.

**Comment by gdosh** [comment]
Update.. 
CoWin Technical Help Center does not know how this has happened, or what to do In order to rectify the problem. 
Personally feel they have shadow banned numbers with frequent API calls and this is a server side error and  not a problem with the Extension per se.

**Comment by cool2srik1** [comment]
Yeah i dont think its a problem with the extension as well. But essential to note that this might happen with frequent hits from same number. So just need to be careful not to use the same number on which you might have already taken a first dose to book for others.

**Comment by dbn1972** [comment]
Cowin is blocking mobile nos who are hitting the servers , one of my friend told he got the call from the cowin  team  initiating blocking his no permanently.

**Comment by cool2srik1** [comment]
Yep confirmed
![IMG_20210608_225029](https://user-images.githubusercontent.com/85451523/121230607-13156a00-c8ad-11eb-9ef5-25d075c42172.jpg)

**Comment by DakshK579** [comment]
This here requires more justification but dont worry cowin saying its an system glitch and affected users to wait for 24hrs

**Comment by dbn1972** [comment]
Officially cowin now blocking all the mobile nos running bots or violating their terms of service ,please go through it.

**Comment by DakshK579** [comment]
> Officially cowin now blocking all the mobile nos running bots or violating their terms of service ,please go through it.

Brother i also use and i dont face any of this issue you should always login when slots come in your area and dont use auto refresh

**Comment by DakshK579** [comment]
in group no one having this issue at all

**Comment by samdsai** [comment]
> This here requires more justification but dont worry cowin saying its an system glitch and affected users to wait for 24hrs

I too facing this issue since last 2 days .I am not sure are they really going to unblock the mobile after 24 hrs , Now for me it is more than 48 hrs  still facing same issue.

**Comment by cool2srik1** [comment]
> > Officially cowin now blocking all the mobile nos running bots or violating their terms of service ,please go through it.
> 
> Brother i also use and i dont face any of this issue you should always login when slots come in your area and dont use auto refresh

Lol. These are some new rules. Dont count on it though, they might block any number which uses bots.  We wouldn't be fighting so hard for slots had there been enough vaccines or of there was a better system. Thanks to people like shushrut some of us have been able to book slots. But now it seems to me we have to again toil to book slots manually. 

And I dont know what  will happen to those people who have to book dose 2 from the same number. note that they need both doses booked from same number to get the certificate. I dont know why the aadhar linkages
are not coming handy. I am closing this issue as it is not an issue with the extension per se.
