### ISSUE TITLE
URGENT !! Cowin is BLOCKING NUMBERS.

### ISSUE THREAD

**Issue by gdosh** [sushrut111/cowin-automation-extn#109]
This is not an error. 
But I didn't know where else to make it known. 

Past 2 days I was Unable to login due to NO OTP.

Contacted CoWin Technical support, they said that I generated > 200 OTP in 24 hrs ((I didn't- I go online for 3 hrs per day. max I generate is 80-90 OTP)).
Anyways, they banned my number for "असामान्य गतिविड़ी" means = abnormal activity. 

They said to try logging in after maybe 24 hrs, as it's a system generated software block.

**Comment by sushrut111** [comment]
Ohh, didn't notice any such thing yet. 
Thanks for letting us know. 

You probably want to start a discussion.
