### ISSUE TITLE
ADD date 

### ISSUE THREAD

**Issue by Sarangm3** [sushrut111/cowin-automation-extn#111]
plz give option of date
bcoz some time i got today vaccine but i want  tomorrow.

**Comment by lucifer6056** [comment]
> plz give option of date
> bcoz some time i got today vaccine but i want tomorrow.

Just enter 1 in the field "skip days" and tomorrow's slot will be selected

**Comment by Sarangm3** [comment]
> > plz give option of date
> > bcoz some time i got today vaccine but i want tomorrow.
> 
> Just enter 1 in the field "skip days" and tomorrow's slot will be selected

thx
