### ISSUE TITLE
hard reset cache before clicking calling search API

### ISSUE THREAD

**Issue by dhruv5harma** [sushrut111/cowin-automation-extn#112]
I am not able to see slots on browser while extn refreshing the page as its Loding page from same cache, meanwhile if i open the same page in incognito mode i am able to see the new slots

**Comment by dhruv5harma** [comment]
when i do something like ctrl+f5, i am able to see new slots

**Comment by dhruv5harma** [comment]
FYR : https://www.youtube.com/watch?v=hf44_-qqddY

**Comment by sushrut111** [comment]
Saw the video. Great finding. 
However, I do not plan to add cache clearing mechanism to the extention.

Just in case if any reader thinks that extension is causing the stale results, please be informed that caching is added by cowin portal itself and extension does not play with it.
