### ISSUE TITLE
[v3.1.0] Allow users to customise the interval between auto refresh on district search

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/cowin-automation-extn#12]
- Currently with the option `Enable Auto Refresh`, the search button is clicked every 2 seconds
- This interval should be customisable
- However this is not straightforward, because this interval is handled as part of findSlotAndBook() - a separate async thread

**Comment by sushrut111** [comment]
@kapishmalik 
Here is another issue, if you are interested.

**Comment by kapishmalik** [comment]
Sure I ll take this up

**Comment by sushrut111** [comment]
@kapishmalik Please let me know if you need any help. 
Also, if you will not be able to take this up at the moment, we can keep this issue open to others if anyone is interested, thanks!

**Comment by kapishmalik** [comment]
Hey you can keep this issue as opened. I didn't get time today.

**Comment by sushrut111** [comment]
> Hey you can keep this issue as opened. I didn't get time today.

Thanks for letting me know!

**Comment by sushrut111** [comment]
Fixed in https://github.com/sushrut111/cowin-automation-extn/releases/tag/v3.3.0-autorefresh
