### ISSUE TITLE
Add option to book for multiple beneficiaries

### ISSUE THREAD

**Issue by manasshukla1** [sushrut111/cowin-automation-extn#19]
@sushrut111 Please add an option to book slots for multiple beneficiaries and to optional option to select own preferred centre.

**Comment by p4i1** [comment]
> @sushrut111 Please add an option to book slots for multiple beneficiaries and to optional option to select own preferred center.

1. booking of Multiple beneficiaries is disabled by cowin.
2. center preference is added in the latest update. chrome extension will take time to update. 
2a) you can use the Mozilla extension which is updated
2b) can add the extension manually in chrome. instructions are provided in the readme.
@sushrut111 please correct if mis-informed.

**Comment by sushrut111** [comment]
Thanks for responding @p4i1 
The information is correct

**Comment by manasshukla1** [comment]
@p4i1 @sushrut111 
1. Booking of multiple beneficiaries is  not disabled. You can easily book through python script, please refer this(github.com/pallupz/covid-vaccine-booking).

If the same can be implemented in this extension then it would be great.
Thanks.

**Comment by sushrut111** [comment]
@manasshukla1 This extension exclusively runs on top of the cowin portal (https://selfregistration.cowin.gov.in/)
Cowin portal has disabled option to book for multiple beneficiaries. It was available before - and the extension supported that as well, but right now it if disabled.

The python script you mentioned is independent client with its own UI(CLI) and does not run on the top of cowin portal. Naturally it is not very friendly with the people who do not know what python is or how to run a program. 

This extension is created mainly to counter that only people who understand programming should benefit. This extension allows people who do not come from programming background, benefit from the powers of programming.

**Comment by manasshukla1** [comment]
> @manasshukla1 This extension exclusively runs on top of the cowin portal (https://selfregistration.cowin.gov.in/)
> Cowin portal has disabled option to book for multiple beneficiaries. It was available before - and the extension supported that as well, but right now it if disabled.
> 
> The python script you mentioned is independent client with its own UI(CLI) and does not run on the top of cowin portal. Naturally it is not very friendly with the people who do not know what python is or how to run a program.
> 
> This extension is created mainly to counter that only people who understand programming should benefit. This extension allows people who do not come from programming background, benefit from the powers of programming.

Well that's also fine.
