### ISSUE TITLE
Make the autofill form look better

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/cowin-automation-extn#2]
The form which collects the data to be filled in the portal looks like this currently:

![Screenshot 2021-05-15 at 8 58 36 PM](https://user-images.githubusercontent.com/11269256/118369073-a4503400-b5c0-11eb-9266-7d40225373db.png)

it could look better by making use of some css frameworks.
Steps to get this form (reproduce the issue):
1. Clone the repository
2. Load the extension to chrome browser by using load unpacked option at [chrome://extensions](chrome://extensions)
3. Go to [https://selfregistration.cowin.gov.in/](https://selfregistration.cowin.gov.in/)
4. Click on the button "click to edit autofill inputs"

**Comment by prayuj** [comment]
Hi @sushrut111 , I can take this issue up. I'll use bootstrap!

**Comment by sushrut111** [comment]
Sure. Please go ahead. I hope you have checked how the elements are created and there isn't any HTML file.
Feel free to reach out if you need any clarifications.

**Comment by sushrut111** [comment]
Assigned to you

**Comment by sushrut111** [comment]
Fixed in #7 
Thank you so much @prayuj
