### ISSUE TITLE
Need More Filter Two Minutes Jobs

### ISSUE THREAD

**Issue by rishrockstar** [sushrut111/cowin-automation-extn#20]
Hi,
Like You Added Age Group Filter
Same Add for 
Vaccine Name: Covidshield/Covaxin/Spuntik V
Amount: Paid/Free

It will be more precise for automate booking

**Comment by p4i1** [comment]
That feature added in the latest update. chrome extension will take time to update.
2a) you can use the Mozilla extension which is updated
2b) can add the extension manually in chrome. instructions are provided in the readme.


> Hi,
> Like You Added Age Group Filter
> Same Add for
> Vaccine Name: Covidshield/Covaxin/Sputnik V
> Amount: Paid/Free
> 
> It will be more precise for automate booking

**Comment by rishrockstar** [comment]
Yup, I had seen after pulling code.
