### ISSUE TITLE
Please add option to set refresh time

### ISSUE THREAD

**Issue by amankapoor** [sushrut111/cowin-automation-extn#21]
Hi, please provide an option to change refresh time. The current refresh time of 2 seconds triggers something as they show a toast notification saying 'something went wrong' after multiple refreshes.

Also, it may lead to more severe restriction by their firewall because it has happened with me when I was playing with their API and exceeded the rate limit.

Thanks again for this extension. Ability to choose the center is the best feature.

**Comment by amankapoor** [comment]
I manually changed the code to set refresh interval as 10s, but I still got 'something went wrong' error. The problem might be something else. 
![image](https://user-images.githubusercontent.com/8210816/119259791-923c4a00-bbed-11eb-9a93-1d866b3d43c1.png)

**Comment by sushrut111** [comment]
https://github.com/sushrut111/cowin-automation-extn/releases/tag/v3.3.0-autorefresh
