### ISSUE TITLE
Not getting otp but leaves with an error need help with it

### ISSUE THREAD

**Issue by Dhanushrajashekar** [sushrut111/cowin-automation-extn#25]
![tempsnip](https://user-images.githubusercontent.com/70057181/119331312-d6d6ec80-bca4-11eb-8bb0-75b6d8305c4e.png)

**Comment by p4i1** [comment]
@Dhanushrajashekar that's the new update from cowin. to bypass 180s cooldown either use VPN to india or change your network.
