### ISSUE TITLE
Not working in kiwi

### ISSUE THREAD

**Issue by rishi684** [sushrut111/cowin-automation-extn#29]
In past it working fine in kiwi browser. But now above edit button not working. Whenever i click popup not open to edit details
![Screenshot_2021-05-25-10-38-29-279_com kiwibrowser browser](https://user-images.githubusercontent.com/84761860/119442400-63d18280-bd45-11eb-83eb-a9ba86a362ee.jpg)

**Comment by sushrut111** [comment]
The extension has been updated now and should be working.

**Comment by rishi684** [comment]
Thnx.. now its working
