### ISSUE TITLE
Similar Working for UMANG website

### ISSUE THREAD

**Issue by anuppanjabi** [sushrut111/cowin-automation-extn#39]
I believe Umang website shows the slots earlier than the COWIN website and there is no CAPTCha there . Can u please try make something similar to this for the Umang Website .

**Comment by sushrut111** [comment]
I am not sure if I am going to take up one more extension.

I am not sure if umang does not really need captcha, else that will be very wrong for everyone who does not know that.

Let us see.

**Comment by anuppanjabi** [comment]
Both Umang and Arogya Setu don't need Captcha . Try buddy.  Just check the interface it's really very simple !
