### ISSUE TITLE
I dont see captcha captcha working now. 

### ISSUE THREAD

**Issue by venfah** [sushrut111/cowin-automation-extn#40]
Now we see it is able to go to booking page and not able to fill the captcha. waiting there for-ever

**Comment by dkvyas** [comment]
Can we have some kind of sound so manually enter captcha control in this chrome extension?

**Comment by sushrut111** [comment]
> Now we see it is able to go to booking page and not able to fill the captcha. waiting there for-ever

If you click the slot manually instead of letting the extension do it, the captcha will not be filled. I know this was an issue and @prayuj has fixed it in v4.0.0



> Can we have some kind of sound so manually enter captcha control in this chrome extension?

We could have, but there are limitations for inclusion of sounds.
