### ISSUE TITLE
Captch decoder logic

### ISSUE THREAD

**Issue by bpanigrahi** [sushrut111/cowin-automation-extn#49]
Can you please share some info on how the captch decoder works. 

Also, please point me to that code block of captch decoder.

**Comment by sushrut111** [comment]
Sure. I am thinking of writing it down.
For the code, you can find the enterCaptcha function in the contentScript.js file.

**Comment by prayuj** [comment]
> 
> 
> Can you please share some info on how the captch decoder works.
> 
> Also, please point me to that code block of captch decoder.

It will blow your mind once you get how the captcha decoder works. Huge Kudos to @sushrut111 for the development. Waiting for that article 😄. Really smart engineering 🎊 !

**Comment by rayarindam2111** [comment]
Great improvisation!
The UMANG api, however does not require a captcha for booking vaccine slots.
You can try this project out: [Co-WIN-automated-slot-booking](https://github.com/rayarindam2111/Co-WIN-automated-slot-booking).

**Comment by sushrut111** [comment]
@rayarindam2111 Great work man! 
You must already be aware, but UMANG is not very stable it seems. Many times, it did not let me log in.

**Comment by rayarindam2111** [comment]
Couldn't agree more. However, once you login, the UMANG token itself remains valid for 24 hours, so the UMANG login itself is a one-time process. 
Moreover, when the demand goes high, I've noticed that the Co-Win server crashes more frequently while the UMANG endpoints hold more stable. The bookings I've made till now have been relatively hassle-free. Just a purely personal observation!

**Comment by sushrut111** [comment]
I saw the cowin token that umang fetches is valid just for 15 mins as it is on the cowin portal. Not sure how you could be logged in for 24hrs. I will check this out. 

This is not the correct place for discussion I guess. I would suggest you open a discussion thread in this repo or ping me on telegram https://t.me/sushrut111

**Comment by rayarindam2111** [comment]
The UMANG login token is valid for 24 hours - this login endpoint is the one that is not fail-safe and errors out frequently. The Co-Win login inside UMANG is however fairly fail-safe and works without issues - this login token needs to be refreshed every 15 minutes. 

Sure, I'll go ahead and open a discussion thread on this. Thank you!

**Comment by sushrut111** [comment]
@bpanigrahi @prayuj Finally wrote it down: http://bit.ly/captcha-decode-dev
