### ISSUE TITLE
slot booking not working

### ISSUE THREAD

**Issue by mesumitm** [sushrut111/cowin-automation-extn#50]
Even though the 15mins refresh works but the slot booking doesn't work even after selecting the preference. I can't see any movement on the screen whenever any slot is updated with the selected preference. Am I missing anything? I am using the latest version 3.7.0

**Comment by sushrut111** [comment]
Are you setting auto refresh? Could you check latest version and see if you are still facing it? Please update this with more information for us to check!

**Comment by sushrut111** [comment]
Please reopen if you would like to give more info. Closing it cosnidering this is resolved.
