### ISSUE TITLE
Vaccine filter is not working in 4.0

### ISSUE THREAD

**Issue by Ronak1991** [sushrut111/cowin-automation-extn#55]
The vaccine filter is still not working. I had selected Covaxin but the booking is confirmed for Covishield.

**Comment by Ronak1991** [comment]
This issue is coming when we mention a center in a preferred center column in which Covishield are available.

**Comment by sushrut111** [comment]
Can record the screen so that I can get a better idea? Given the recent changes that we did, this is not ought to happen.

**Comment by sushrut111** [comment]
Closing for now, please reopen if issue persis.
