### ISSUE TITLE
Indicate what the beep is for

### ISSUE THREAD

**Issue by rohilv** [sushrut111/cowin-automation-extn#57]
Hi, 

I filled the form and set the refresh timer to 10secs. 
I am getting beep on every 5/10secs but It is not proceeding ahead or showing any available slots. 
I have applied filters like **18+** and **free**. I tried removing the **free** filter but it's the same. 
I am also searching by District (Mumbai) and have mentioned my nearby address keywords in the input box provided.

**Comment by rohilv** [comment]
OKay.
I just realised the beep was for session timeout (shown in document /tab title) 
Just a suggestion, the indication could be better.
you can close this issue if you think it's irrelevant or suggestion won't be picked up

**Comment by sushrut111** [comment]
Suggestion is great and I understand the utility. Just that we are kind of working more towards the main functional stability. 

If you are skilled for it, I would suggest you to go for it! Your suggestions/feedbacks/contributions are always welcome.

**Comment by sushrut111** [comment]
If anyone would like to take this issue up, you are welcome to do so!

**Comment by rohilv** [comment]
Options:
1. Add it to Wiki / Readme.md
2. Show a popup notifying the user about the session timeout and show possible action items. i.e. redirect to homepage.
3. Auto redirect to cowin home page asking for new OTP; This will automatically send another OTP on the user's mobile
4. Ask the user if he wants a session timeout notification beep or popup

**Comment by sushrut111** [comment]
@rohilv Why don't you take up this issue?

**Comment by sushrut111** [comment]
Original beep is now replaced with voice.
We will take care of rest of the things when we can.
