### ISSUE TITLE
Refactor contentScript.js

### ISSUE THREAD

**Issue by prayuj** [sushrut111/cowin-automation-extn#58]
Hi!
Currently the `contentScript.js` includes two main parts in it, namely:
- The main logic of the automation which includes auto filling, filter selection, auto refresh, captcha fill, etc.
- The other is the HTML content that is injected onto the website which includes the Button on the upper left which triggers the Form Modal.

It would be nice to have the HTML part in a separate js file for better development and cleaner code. 
Additionally, the code can also be cleaned up as there are some unused lines of code and a bunch of comments!

**Comment by rohilv** [comment]
taken

**Comment by prayuj** [comment]
Assigned it to you!
