### ISSUE TITLE
Selecting booking for member 

### ISSUE THREAD

**Issue by rohilv** [sushrut111/cowin-automation-extn#59]
Issue: After every renewal of the session the user is taken to the Login / OTP page, after which, a member selection screen appears which is currently not automated and waits for the user's input. 

![Cowin-members-blur](https://user-images.githubusercontent.com/3790213/120103431-2ddd3580-c16d-11eb-9811-430045256a49.png)

User can be asked to input the position of the member he intends to schedule the slot for. (For Eg, 1st User, 2nd User)

**Comment by sushrut111** [comment]
That is a great suggestion. 
The thing is once the member is selected automatically (of course, within a moment!) there will be no way to see if that was a correct member until you see the captcha screen - which is also automated. The search page (where you search by district or pincode) does not show any name there - it is a blind game - too confusing, isn't it? Therefore, let this be a point of manual intervention!
