### ISSUE TITLE
Error Message : Something Went Wrong, Please try again!

### ISSUE THREAD

**Issue by prakhar-agr** [sushrut111/cowin-automation-extn#63]
Hi, 
First of all, a very thanks to you for this superb extension.
I have been using this app from your first release, and as of it, i need to acknowledge few glitches i found using the extension of chrome:
1. Initially, extension omits paid slots on selecting the free checkbox, but from last 2-3 days inspite of selecting free slot, paid slots are being booked.
2. Secondly, one of the major issue iam facing is the error "**Something went wrong, please try again!**" in red notification bar in bottom left. However, auto-search is still on, and it just dont allow the captcha to be entered automatically. This error appears continously, and is resolved by changing the internet connection. I use 3 hotspots, and interchange the connections every 40-50 seconds as of this issue. 
3. Time interval auto-refresh gets little more faster when filters are applied, like if you have selected 10 seconds interval for autorefresh, but if you select filters (free/paid), it automatically refresh within 2-3 seconds (along with filter refresh).

However, as of this extension, i have helped more then 500 people who do not have internet knowledge to book the slots.
A very big Thanks for the extension.

**Comment by prakhar-agr** [comment]
One more addon to Point No. 2, this issue is keeping persisting even when you do not refresh the page or execute the script(on dashboard). 
I feel this issue is coming as of Logout timer sending multiple requests, as title keeps tickling too frequently.

**Comment by sushrut111** [comment]
Which version are you using?
Are you sure it is refreshing (searching again)?

Is it possible that you are mistaking filter application as refresh?

**Comment by prakhar-agr** [comment]
Previously, i was using older version, but recently updated to 4.0.1, and the issue persists.
Yes, its' refreshing. Iam uploading the video for your reference.
Iam very much sure, it's refreshing, not filter application.  Even after multiple errors popping up, after couple of auto-refreshes, the final booking screen appeared 3-4 times.  


https://user-images.githubusercontent.com/85110242/120340942-155b4f80-c314-11eb-8f5c-13c74e54d733.mp4

**Comment by sushrut111** [comment]
What refresh interval did you set? Can you show me in the video while it is happening?
Also can you guide me how I can reproduce this issue? I mean what all the things you did so that it started doing this?

**Comment by prakhar-agr** [comment]
Interval is set to 5 seconds. Sure, but that happens randomly.
I actually did nothing, it's working for me. I generally switch to different internet connections.

**Comment by sushrut111** [comment]
In the video the refresh seems to be faster than once per 5 seconds. 
Also do not set refresh as five seconds, each of the searchRequest takes 2 backend calls.

**Comment by prakhar-agr** [comment]
That's what i addressed in point no 3. Auto-refresh rate is quite frequent then entered value.
Setting up longer refresh rate reduces the booking chances though.

**Comment by sushrut111** [comment]
> That's what i addressed in point no 3. Auto-refresh rate is quite frequent then entered value.

That's what.  I am not able to reproduce this issue and would need your help. 

> Setting up longer refresh rate reduces the booking chances though.
It is limitation from cowin

**Comment by prakhar-agr** [comment]
Is there anything that can be done to avoid API rate limits?

**Comment by sushrut111** [comment]
No

**Comment by prakhar-agr** [comment]
No issues, multiple connections resolves my issue.

> No
