### ISSUE TITLE
Tool not working across multiple tabs

### ISSUE THREAD

**Issue by anilonline1370** [sushrut111/cowin-automation-extn#64]
I tried accessing search by district in first tab and search by pin code in second tab. When I write this in console '_console.log(window.localStorage.getItem("searchpref"))_;' , I get pincode instead of district in first tab. And I feel this affects the working of the bot as it is not able to successfully book available sessions.
Suggestion to solve this issue -
https://stackoverflow.com/questions/12617536/store-browser-tab-specific-data

**Comment by sushrut111** [comment]
It's not made for multiple tabs. I am aware of this.
