### ISSUE TITLE
Get extension update notification 

### ISSUE THREAD

**Issue by msnitish** [sushrut111/cowin-automation-extn#65]
Can we have a feature to get a notification in some way which tells us to update the chrome extension ? I see changes being made to the bot every day and when the new changes are pushed to the chrome web store, does my extension also get updated automatically ? @sushrut111

**Comment by sushrut111** [comment]
The extension installed from chrome web store gets updated automatically when a new version is available in the store. However chrome store takes some time to review and publish the new version on the store.
If you are interested in new version getting released on github, you will have to manually install when a new version becomes available.
I generally post the updates to a telegram channel. You can join it here: https://telegram.me/cowinbooking

**Comment by msnitish** [comment]
Thank you.
