### ISSUE TITLE
Setting skip days  to 1 still books today's slot in case center provides option for both vaccines

### ISSUE THREAD

**Issue by swapnilt2** [sushrut111/cowin-automation-extn#71]
I have set skip days to 1.
It still books today's slot in case center provides option for both vaccines.

Refer yellow highlighted part in attached image, where covaxin slot is skipped, but covishield slot is booked for today, even though i have set skip days to 1.

<img width="449" alt="sshot-1" src="https://user-images.githubusercontent.com/85155474/120284313-c1337980-c2d9-11eb-8e9f-d282ddee7336.png">

This seems to be bug in script algorithm.

Can you resolve this issue to make this wonderful utility even better.
Thanks.

**Comment by sushrut111** [comment]
Makes sense. This could be an issue. We will check.

**Comment by sushrut111** [comment]
Fixed in #79
