### ISSUE TITLE
state and district name are not filling automatically

### ISSUE THREAD

**Issue by deeps69** [sushrut111/cowin-automation-extn#74]
yesterday it was working fine but today when i went to check the slot the state name and the district name are not filling automatically. i have tried doing it again and again but same problem. i think it is some kind of bug pls fix it. 
really helpful extension. ( version 4.0.1)
thankyou

**Comment by rrrrravichandra3** [comment]
Even I noticed this issue and it's intermittent.

**Comment by prakhar-agr** [comment]
Even iam facing the same issue, but it gets auto-fill when you click on Pincode tab and back on District. Try Twice. It works for me.

**Comment by sushrut111** [comment]
If you are using extension, please stick to the search mode you select in the extension. The flow is optimised for automatic booking. Manually changing mode will interrupt that.

If your internet connection is slow, you may see intermittent issues while selecting State/District as the list takes a while to load on slower connection.
