### ISSUE TITLE
Error Message : Something Went Wrong, Please try again! 

### ISSUE THREAD

**Issue by rrrrravichandra3** [sushrut111/cowin-automation-extn#75]
Great extension. It's working fast.

I checked the network tab and it is making 4 api calls after refresh interval time. 

Previously it used to make 1 or 2 api calls every refresh interval time.

Making 4 calls is reaching API limit and thereby error message. I checked other cowin booking automations and they make 1 api call every refresh interval time.

**Comment by sushrut111** [comment]
Cowin changed something today, even without extension it is making  requests.
