### ISSUE TITLE
Token gets expired in 3 mins now instead of 15 mins

### ISSUE THREAD

**Issue by jivanpuri** [sushrut111/cowin-automation-extn#76]
Token gets expired in 3 mins now instead of 15 mins; can you please set it to 3 mins default or externalize that as input. This would be a huge help.

**Comment by sushrut111** [comment]
The extension does not count 15 minutes, it checks the users token which contains expiration time. So if the cowin changes something session expires in 1 minute, the extension will get the correct expiration time and show it to you.

FYI, I just checked session does not expire in 3 minutes.
