### ISSUE TITLE
Cowin error "too many search requests"

### ISSUE THREAD

**Issue by azimb** [sushrut111/cowin-automation-extn#80]
Noticed today that while running the automation tool, whenever Search is hit, cowin complains "Too many search requests, please try after sometime!" (see screenshot below).

This is news to me, as the refresh interval hasn't been changed from 10 seconds.

![image](https://user-images.githubusercontent.com/38919150/120474280-a3434300-c3c5-11eb-95fd-f5fe1a773e3f.png)

**Comment by azimb** [comment]
refresh interval is extended to `15 seconds`, but still seeing the same error

**Comment by azimb** [comment]
logged out and re-logged in, and I don't get that anymore. I will verify whether this fix is temporary or permanent

**Comment by azimb** [comment]
logged out and re-logged in, refresh interval is set to 15 seconds:

**same error, after about 5 minutes.**

**Comment by Kroggieboy57** [comment]
I had set it to 30 and got it

**Comment by azimb** [comment]
got what, a successful booking, or got this error?

**Comment by bhattankitk** [comment]
Tried with `50 seconds` interval and the same error `too many search requests` stopped!!


But in 10 mins, I found below error for 502 status, I think it's server error.
![image](https://user-images.githubusercontent.com/3056708/120521253-5de93a80-c3f2-11eb-851b-cdcca6ef7a6e.png)

**Comment by azimb** [comment]
BTW - I was constantly getting that error but soon realized that it was still searching fine. And the tool also worked and booked an appointment :) thanks to @sushrut111 and team

**Comment by sushrut111** [comment]
I and @prayuj are looking at this. This is mainly due to a change in cowin portal. They seem to have made the rate limiting more restricted.

**Comment by sushrut111** [comment]
Too many requests error is gone now by design of the cowin portal.
