### ISSUE TITLE
Automation End To End

### ISSUE THREAD

**Issue by GAGSKHANNA** [sushrut111/cowin-automation-extn#82]
Thanks a lot to you, I was able to book 100’s of slots for my friends, family, maids, my driver etc without your utility it would have been very difficult 🙏
Is it possible to have automation from end to end from reading the otp to booking?

**Comment by sushrut111** [comment]
We do not currently have plans for end to end automation - because to enable it, the users may need to have some technical background on different topics -  making it biased towards only those who can do it.
