### ISSUE TITLE
Automate OTP entering from mobile browsers

### ISSUE THREAD

**Issue by kamlekar** [sushrut111/cowin-automation-extn#83]
Looks like OTP entering can be automated as per this article: https://web.dev/web-otp/

There are some demos available online: https://jyotishman.github.io/webOTPAPI/

Can someone please have look at it?

**Comment by sushrut111** [comment]
Will look into it.

**Comment by sushrut111** [comment]
We cannot use the webOTP api as it requires the SMS to be sent in a particular format which is out of our control.
