### ISSUE TITLE
No captcha code and now I am getting logged out every single minute.

### ISSUE THREAD

**Issue by ipankajsingh** [sushrut111/cowin-automation-extn#85]
Is this anyhow related to this extension ? some kind of blacklist or anything

![image](https://user-images.githubusercontent.com/24999656/120686516-ab32de00-c4be-11eb-9478-efad07309d2d.png)

**Comment by deepak1977** [comment]
I think captcha is not coming from CoWIn side. So, its a relief for the end users.

**Comment by ipankajsingh** [comment]
> I think captcha is not coming from CoWIn side. So, its a relief for the end users.

But will the extension work ? coz it is not working at all bcoz it might be trying to fill it and it's not able to so the loop never completes

**Comment by lucifer6056** [comment]
> Is this anyhow related to this extension ? some kind of blacklist or anything
> 
> ![image](https://user-images.githubusercontent.com/24999656/120686516-ab32de00-c4be-11eb-9478-efad07309d2d.png)

I faced the same issue today at 6 pm no captcha was present, even when I manually tried to select the slots it showed all slots booked for the time slot

**Comment by sushrut111** [comment]
Will be fixed in #86
