### ISSUE TITLE
coWIN has removed captcha code.

### ISSUE THREAD

**Issue by ipankajsingh** [sushrut111/cowin-automation-extn#86]
Just got to know that they have removed the captcha code and decreased the limit to 20 per minute.
and I was thinking why my booking is not getting created automatically.
Please update the extension ASAP so that we can get the dose

**Comment by AshishNamdev** [comment]
@sushrut111 I  have just noticed  auto confirm code is inside enterCaptcha function, which the following one.

``
setTimeout(() => {

    if (enableautoconfirm) $("ion-button.confirm-btn")[0].click();
  }, 500);
``

And now Cowin Platform have removed CAPTCHA so this could be the probable issue of the click event not happening on `Confirm` button.

Can you please check and confirm so I can take this up tomorrow ?

**Comment by sushrut111** [comment]
@AshishNamdev this is the issue. Feel free to take it up. Thanks

**Comment by ipankajsingh** [comment]
it would be so nice if we can have the new version ASAP. So many slots came and went by

**Comment by ipankajsingh** [comment]
> @AshishNamdev this is the issue. Feel free to take it up. Thanks


> @sushrut111 I have just noticed auto confirm code is inside enterCaptcha function, which the following one.
> 
> ```
> setTimeout(() => {
> 
>     if (enableautoconfirm) $("ion-button.confirm-btn")[0].click();
>   }, 500);
> ```
> 
> And now Cowin Platform have removed CAPTCHA so this could be the probable issue of the click event not happening on `Confirm` button.
> 
> Can you please check and confirm so I can take this up tomorrow ?

They might re-introduce it later, so keep a check if captcha present then decode or go ahead

**Comment by sushrut111** [comment]
Fixed: https://github.com/sushrut111/cowin-automation-extn/releases/tag/v4.1.1

**Comment by sushrut111** [comment]
@ipankajsingh taken care of that already.

**Comment by ipankajsingh** [comment]
@sushrut111 extension doesn't work anymore.
Using latest version , even if there is no captcha, it doesn't book nor select the preferred time.

**Comment by sushrut111** [comment]
@ipankajsingh which version did you use?

**Comment by ipankajsingh** [comment]
the one released last night after removing the captcha decode thing.

**Comment by sushrut111** [comment]
Would be great if you specify version. Anyway, use v4.1.2 - this is the latest with the fix. Let me know if that doesn't work either.

**Comment by ipankajsingh** [comment]
yeah I was on 4.1.1, just tested 4.1.2
It is working but I can't believe that even the automated script isn't fast enough to book a slot.

**Comment by sushrut111** [comment]
>I can't believe that even the automated script isn't fast enough to book a slot.

There seems to be a competition between script users now.
@ipankajsingh

**Comment by ipankajsingh** [comment]
> > I can't believe that even the automated script isn't fast enough to book a slot.
> 
> There seems to be a competition between script users now.
> @ipankajsingh

Yeah, vaccination has become a hackathon now
