### ISSUE TITLE
Sushrut have you removed the extension from chrome web store

### ISSUE THREAD

**Issue by lucifer6056** [sushrut111/cowin-automation-extn#87]
<img width="960" alt="2021-06-03 (1)" src="https://user-images.githubusercontent.com/85309226/120689546-dd920a80-c4c1-11eb-8087-0ba8d059e4f5.png">
<img width="960" alt="2021-06-03" src="https://user-images.githubusercontent.com/85309226/120689598-ea166300-c4c1-11eb-8dc0-bb9189265ca3.png">
I searched the web store for this extension and sadly no result showed up and when i deeply scrolled down then there was **_this guy_** with same name as of your extension

**Comment by sushrut111** [comment]
I removed my extension from chrome store.
My extension is open source so anyone can build over it and distribute it - given they credit my work.
