### ISSUE TITLE
Do you have any active telegram group

### ISSUE THREAD

**Issue by lucifer6056** [sushrut111/cowin-automation-extn#89]
I want to join for staying updated with the latest extension updates
![image](https://user-images.githubusercontent.com/85309226/120698548-d58b9800-c4cc-11eb-8934-babc3fd83bbc.png)

**Comment by sushrut111** [comment]
There is (https://t.me/joinchat/2l17jl8xYRM1NTdl), but this is for general discussion.

**Comment by lucifer6056** [comment]
> There is (https://t.me/joinchat/2l17jl8xYRM1NTdl), but this is for general discussion.

thnx just joined
