### ISSUE TITLE
Option to select preferred vaccination centre also.

### ISSUE THREAD

**Issue by enigmatic241** [sushrut111/cowin-automation-extn#9]
There should be an option available to select vaccination centers also so that anyone will be able to get bookings for their preferred vaccination center only.

**Comment by sushrut111** [comment]
Hi this issue has been addressed in v3.x, please check that out in releases.
1. https://github.com/sushrut111/cowin-automation-extn/releases
2. https://github.com/sushrut111/cowin-automation-extn/wiki/How-install-extension-manually-from-github-release--(Before-the-version-is-published-to-chrome-web-store)
