### ISSUE TITLE
Unable to book slot even selected last option in form "Confirm" button "Auto" click.

### ISSUE THREAD

**Issue by samdsai** [sushrut111/cowin-automation-extn#90]
@sushrut111 , Yesterday I was booking slot for covaxin , I got multiple slot for booking but none of the slot got confirmed even though I have selected "Confirm" button "auto" click option , It was showing the me the slot and stuck on confirmation screen even manually pressing confirm button it was not working . I am not sure it is some issue with browser or my network (Using Ril Dongle not wired broadband) . The I changed the browser from Chrome to MS Edge , but still issue is same . 
Can you help, what could be the reason ?

**Comment by sushrut111** [comment]
Extension was not working because captcha was removed. 
I have fixed it in v4.1.2, download and install from releases. 

Find instructions in wiki.
