### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by bonyjose** [sushrut111/cowin-automation-extn#93]
can you port this to Firefox and submit in Firefox extension store/it may have a longer chance to survive in the store

**Comment by sushrut111** [comment]
@bonyjose What do you meant by "it may have longer chance?"

This was available for firefox but some functionalities seem to not work. So I took it down.

**Comment by bonyjose** [comment]
> @bonyjose What do you meant by "it may have longer chance?"
> 
> This was available for firefox but some functionalities seem to not work. So I took it down.

I meant the addon will have a greater chance to survive in the firetox extension store, because i assumed the extension is no longer available in chrome store because it might not be following the store guidelines.

**Comment by sushrut111** [comment]
It is not available in chrome store because I took it down.
