### ISSUE TITLE
The page automatically logs out after 5 mins exactly 

### ISSUE THREAD

**Issue by Dhanushrajashekar** [sushrut111/cowin-automation-extn#95]
And  i found 2 or 3 slot booking but it aint showing captcha in it i think they removed the captcha its only showing the time and confirm button

**Comment by gdosh** [comment]
I believe the logout is from the server side. Ie: CoWin portal. The portal is logging you out because of excess API calls from your IP. 
If you increase the refresh interval to say about 40-50, it will log you out after about 12-13 minutes.

**Comment by Dhanushrajashekar** [comment]
> I believe the logout is from the server side. Ie: CoWin portal. The portal is logging you out because of excess API calls from your IP. 
> If you increase the refresh interval to say about 40-50, it will log you out after about 12-13 minutes.

What about the captcha bro? CAPTCHA is not shown in the booking slot

**Comment by sushrut111** [comment]
1. Captcha is removed
2. It's not 5 minutes, it's 20 requests - after which you will be logged out
