### ISSUE TITLE
Extension removed from chrome store

### ISSUE THREAD

**Issue by vickusah** [sushrut111/cowin-automation-extn#96]
![Screenshot (16)](https://user-images.githubusercontent.com/30171144/120826581-3c19c000-c578-11eb-8f63-f7e74a30f9de.png)
why i'm not able to find your extension, whenever i search it show me error "404. That’s an error.

The requested URL was not found on this server. That’s all we know."

**Comment by Dhanushrajashekar** [comment]
> ![Screenshot (16)](https://user-images.githubusercontent.com/30171144/120826581-3c19c000-c578-11eb-8f63-f7e74a30f9de.png)
> why i'm not able to find your extension, whenever i search it show me error "404. That’s an error.
> 
> The requested URL was not found on this server. That’s all we know."

Try to load the extension manually by downloading the zip file. It will work

**Comment by sushrut111** [comment]
I have taken down the extension from chrome store.
