### ISSUE TITLE
Delay and random clicking of selected filters

### ISSUE THREAD

**Issue by kapil-15** [sushrut111/cowin-automation-extn#99]
I use 4 filters and all 4 filters are clicked RANDOMLY [Age 18/Covaxin/Paid/Free] with a maximum delay of 2 Second which has caused me to book a different vaccine which I didn't want to and it misses the slot.

**Comment by dAKsh-Mido** [comment]
This would be treated as User Fault and in this time don't select what vaccine you want just book one which comes all vaccines are good.

P.S: This Issue is treated as Close Now

**Comment by sushrut111** [comment]
But the booking click is synchronised with the filter clicks. I would like to see it in action, can you tell me how I can reproduce it?

**Comment by sushrut111** [comment]
Assuming you are not able to reproduce, closing this. Reopen if needed.
